# Generated by Django 4.2.4 on 2023-09-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_productsimage_employeeimage_customerimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.product')),
            ],
        ),
    ]
